---
abstract: 'MooX::Role::Parameterized - roles with composition parameters'
author:
  - 'Tiago Peczenyj <tiago.peczenyj@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.132661'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Role-Parameterized
requires:
  Class::Method::Modifiers: 0
  Moo: 0
resources:
  bugtracker: https://github.com/peczenyj/MooX-Role-Parameterized/issues
  homepage: https://github.com/peczenyj/MooX-Role-Parameterized
  repository: git://github.com/peczenyj/MooX-Role-Parameterized.git
version: 0.01
